### PR TITLE
Hsdo 293

### PR DESCRIPTION
**Pull request by sherakama**
# Ready for Review:
* 7.x-4.x upgrade to schema and field_collection integration work
* New dependency on stanford_feeds_helper (refactor branch currently)
* New mapping to co-instructor field
* Patches to field_collection

*To test:*
* Pull down on existing site
* pull down feeds_helper module
* Run updates
* Revert features
* Clear caches
* Import stuff.

### CODE REVIEW

**Comment by sherakama** [comment]
Helper PR: https://github.com/SU-SWS/stanford_feeds_helper/pull/2

**Comment by jbickar** [comment]
This is a big 'un.

**Comment by boznik** [comment]
i don't see a version of feeds 2.0-beta8 which is listed as a dependency. not sure which version to use with this?

**Comment by boznik** [comment]
The instructor isn't populating on import.

**Comment by sherakama** [comment]
Latest dev for feeds and field collection.

**Comment by boznik** [comment]
Using latest dev for feeds and field collections and still not getting instructor.

**Pull request closed without merging**
