### PR TITLE
HSDO-320 - New course matrix feature

### PR DESCRIPTION
**Pull request by sherakama**
# Ready for Review

Example site: https://sites.stanford.edu/sws-toggle-block/course-matrix/2016

**To test:** 
- [ ] Build a local JSA site
- [ ] Check out this branch
- [ ]  Download views_matrix contrib module
- [ ] Apply patch found in .make file of this branch
- [ ] drush en stanford_course_matrix
- [ ] Create a new course importer and import something crazy like music or econ
- [ ] Navigate to /course-matrix/2016 and validate:
  1. Page title says: 2016 - 2017 Courses
  2. Seasons are in the correct order starting from Autumn
  3. Instructors are not being duplicated in the output of each cell
  4. Sticky table headers are working
  5. Responsive styles are working

**Test code for:** 
- [ ] Formatting and syntax
- [ ] Approach and design
- [ ] Places for performance improvements

### CODE REVIEW

**Comment by tsui1** [comment]
:moyai::+1:

**Comment by boznik** [comment]
Running "phplint:php" (phplint) task
>> 1 files php linted.

Running "phplint:module" (phplint) task
>> 9 files php linted.

Running "phplint:inc" (phplint) task
>> 38 files php linted.

Done, without errors.

**Comment by boznik** [comment]
This looks good. nice work!

**Comment by sherakama** [comment]
Thanks! 

Are you sure your linters are working? PHPCS in my editor picks up a few issues. 

Also, We need to be better at rebasing. This PR is a mess of commits.

**Pull request merged**
