### PR TITLE
Stanford Courses Minimal Importer

### PR DESCRIPTION
**Pull request by jbickar**
**Not ready yet**

But close...

### CODE REVIEW

**Comment by sherakama** [comment]
Should this be it's own repository? I don't see how this fits in this module other than it relates to courses. I think I would just keep it separate as I can see supporting modules for this cropping up. ie: views, display modes, and permissions.

**Comment by jbickar** [comment]
I could see either way. It uses the content type from stanford_courses. But it declares it as a dependency.

Not sure...

**Comment by sherakama** [comment]
There is a whole bunch of stuff in that main module that I don't think we want when enabling the minimal version. IE: the importer, a number of field base and instances, tampers, strongarm settings, and alters galore. I think this should be on its own for the sake of simplicity and potential gotchas.

**Comment by jbickar** [comment]
I see what you're saying, but if we're using the stanford_course content type from stanford_courses, we want those field bases, instances, strongarm settings, etc. I don't really see this minimal version being used without the parent module. The use case is more like, "Oh, the course importer failed, let's fall back to the minimal version."

**Comment by sherakama** [comment]
Hmm. So you are saying the intent is to have a mix of both minimal and verbose options on one site. I don't think this makes sense. I think they are two very different content models and should require two very different set of views. I'm thinking this is an either or option and not a mix.

**Comment by jbickar** [comment]
Let's get some of our other big thinkers in on this.

**Comment by jbickar** [comment]
So, I think per discussion that this is ready to go. See ECON-20 for future roadmap.

**Comment by jbickar** [comment]
Decided to put this in its own repo after all.

**Pull request closed without merging**
