### PR TITLE
Vpsadev 146

### PR DESCRIPTION
**Pull request by sherakama**
Added author exposed filter.

### CODE REVIEW

**Comment by cjwest** [comment]
Hey Shea,

Created a clean install of JSA with this branch and I can't seem to get the feature to revert. 

screen shot 2015-09-04 at 14 02 38

**Comment by sherakama** [comment]
@cjwest,

I have updated the PR to have a fix in there for the overridden feature.

**Comment by cjwest** [comment]
Hey @sherakama,

It reverted! Yeah! 

So, I see a row count, but no author filter. Is this correct?


screen shot 2015-09-08 at 10 37 54

**Comment by sherakama** [comment]
@cjwest,

Good catch. I completely removed the author filter in that last commit. I have put it back in. Sorry, please have another review.

ps. I should test...

**Comment by cjwest** [comment]
@sherakama 

lol! Good thing we're doing pull requests and testing! 

It worked like a charm this time. Reverted, I see a row count, and the author field works as expected. 
Good work, Shea!

**Comment by sherakama** [comment]
Thanks!

**Pull request merged**
